language: php
php:
  - 5.3
  - 5.4
before_script:
  - wget --quiet http://getcomposer.org/composer.phar
  - php composer.phar install --dev
  - cp phpunit.xml.dist phpunit.xml
  - ~/.nvm/nvm.sh run default vendor/guzzle/guzzle/tests/Guzzle/Tests/Http/server.js &
before_install:
  - ./bin/ci/start_neo4j_server.sh
script: phpunit
jdk:
  - oraclejdk7
